spring:
  application:
    name: SpringBoot-Oracle-MongoDB
  data:
    mongodb:
      uri: mongodb://${USERNAME}:${PASSWORD}@G0240F6BEF2A611-${DBNAME}.adb.us-chicago-1.oraclecloudapps.com:27017/${USERNAME}?authMechanism=PLAIN&authSource=$external&ssl=true&retryWrites=false&loadBalanced=true
      auto-index-creation: true
  threads:
    virtual:
      enabled: true