spring:
  application:
    name: SpringBoot-Oracle-MongoDB
  data:
    mongodb:
      uri: mongodb://${USER}:${PASSWORD}@G0240F6BEF2A611-${DBNAME}.adb.us-chicago-1.oraclecloudapps.com:27017/${USER}?authMechanism=PLAIN&authSource=$external&ssl=true&retryWrites=false&loadBalanced=true
      auto-index-creation: true
#      uri: mongodb://localhost:27017/products
#      database: products
  threads:
    virtual:
      enabled: true